apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      type: backend
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        type: backend
    spec:
      containers:
      - name: postgres-container
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
