apiVersion: v1
kind: Pod
metadata:
  name: redisapp-pod
  labels:
    name: redisapp-pod
    type: backend
spec:
  containers:
    - name: redisapp
      image: redis:latest
      resources:
           limits:
            memory: "128Mi"
            cpu: "500m"
         
      ports:
        - containerPort: 6379