apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    type: frontend
spec:
  containers:
    - name: votingapp
      image: lanre99/votingapp:v2
      ports:
        - containerPort: 80