apiVersion: v1
kind: Pod
metadata:
  name: votingappresult-pod
  labels:
    name: votingappresult-pod
    type: frontend
spec:
  containers:
    - name: votingappresult
      image: lanre99/votingappresult:v2
      resources:
           limits:
            memory: "128Mi"
            cpu: "500m"
         
      ports:
        - containerPort: 80