apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    type: backend
spec:
  containers:
    - name: worker-container
      image: lanre99/votingworkers:v2
      resources:
           limits:
            memory: "128Mi"
            cpu: "500m"
         
      